---

- name: www_pool for servers
  bigip_pool: 
    provider: "{{ f5_provider }}"
    name: www_pool
    lb_method: "round-robin"
    monitors: "/Common/http"
    monitor_type: "and_list"
    state: present
  notify: save config

- name: add pool members
  bigip_pool_member:
    provider: "{{ f5_provider }}"
    port: "{{ hostvars[item].port }}"
    name: "{{hostvars[item].inventory_hostname}}"
    host: "{{hostvars[item].ansible_host}}"
    pool: www_pool
  loop: "{{ groups['webservers'] }}"
  notify: save config

- name: add virtual server
  bigip_virtual_server:
    provider: "{{ f5_provider }}"
    name: "vip"
    destination: "{{ f5_provider.server }}"
    port: "443"
    enabled_vlans: "all"
    all_profiles: ['http','clientssl']
    pool: www_pool
    snat: "Automap"
  notify: save config
  register: vservercache

- name: delay after virtual server changed
  wait_for:
    timeout: 5
  when: vservercache.changed


